---
- hosts: all
  varfile: relay-config.yml
  vars:
    PROJECT_HOME: "/opt/despatch"

  tasks:
    - name: upgrade OS packages
      sudo: yes
      apt: update-cache=yes upgrade=yes

    - name: install OS packages
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
       - python-virtualenv
       - git-core
       - python2.7
       - python-pip
       - nginx

    - name: clone git repository
      sudo: yes
      git: "repo=https://github.com/cloudfleet/despatch.git dest={{ PROJECT_HOME }}"

    - name: install Python packages
      pip: requirements={{ PROJECT_HOME }}/requirements.txt

    - name: create directories
      file: "path={{ PROJECT_HOME }}/{{item}} state=directory"
      with_items:
        - logs
        - run

    - name: restart despatch
      command: "{{ PROJECT_HOME }}/scripts/restart-despatch.sh chdir={{ PROJECT_HOME }}"

