---
- hosts: all
  vars:
    PROJECT_HOME: "/opt/despatch"

  tasks:
    - name: upgrade OS packages
      sudo: yes
      apt: update-cache=yes upgrade=yes

    - name: install OS packages
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
       - python-virtualenv
       - git-core
       - python2.7
       - python-pip
       - nginx
       - supervisor

    - name: clone git repository
      sudo: yes
      git: "repo=https://github.com/cloudfleet/despatch.git dest={{ PROJECT_HOME }}"

    - name: install Python packages
      pip: requirements={{ PROJECT_HOME }}/requirements.txt

    - name: create directories
      file: "path={{ PROJECT_HOME }}/{{item}} state=directory"
      with_items:
        - logs
        - run

    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/nginx.conf

    - name: copy supervisord config file
      template: "src=files/auth-service-supervisor.conf dest=/etc/supervisor/conf.d/auth-service.conf"

    - name: Re-read the Supervisor config files
      command: supervisorctl reread

    - name: Update Supervisor to add the app in the process group
      command: supervisorctl update

    - name: Use Supervisor to restart spire
      command: supervisorctl restart auth-service

    - name: copy relay config file
      copy: "src=files/relay-config.yml dest={{ PROJECT_HOME }}/config/relay-config.yml"

    - name: restart nginx
      service: name=nginx pattern=/etc/init.d/nginx state=restarted enabled=yes

    - name: restart despatch
      command: "{{ PROJECT_HOME }}/scripts/restart-despatch.sh chdir={{ PROJECT_HOME }}"

